apiRules:
- exclude:
    uidRegex: ^GoogleAnalytics
    type: Namespace
- exclude:
    uidRegex: ^Newtonsoft\.Json
    type: Namespace
- exclude:
    uidRegex: ^System\.Net\.Http
    type: Namespace
